namespace NetTool
{
	namespace ValueConverter
	{
		namespace HistoryPage
		{
			[default_interface]
			runtimeclass VisiblityConverter : Windows.UI.Xaml.Data.IValueConverter
			{
				VisiblityConverter();
			}
		}
	}

}
